### ISSUE TITLE
Requirement for block_course_overview that is no longer in core

### ISSUE THREAD

**Issue by thepurpleblob** [roelmann/moodle-theme_flexibase#101]
renderers/core_renderer.php requires blocks/course_overview/locallib.php. This block no longer exists in core after 3.3

**Comment by roelmann** [comment]
Noting that flexibase is **not supported on Moodle3.3+** (primarily due to this reason) What I have not tested is whether it will work if the version of the old course_overview block is installed from the plugins database.
Unfortunately this is due to the decision HQ made when the new dashboard was implemented and rather than deprecating the old block and leaving it in place for a few versions as is normal practice, they straight out removed it :(

**Comment by thepurpleblob** [comment]
Yep - I can't of gathered this but I was just tidying it up really for someone having trouble with course_overview on 3.3+. Answer appears to be not to use flexibase theme. Cheers.
