### ISSUE TITLE
Size of tiles

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#36]
![38 size of icons](https://cloud.githubusercontent.com/assets/687780/12247240/f6bd28a2-b917-11e5-91e6-bf07c824ef7f.png)

These tiles may be a little too big for some tastes.  Maybe they could have a couple of sizes?  I know this is probably a bit of work, but just thinking aloud.

The course tiles probably need a little work from someone with a design eye.  I've been testing out options for bootstrap thumbnails etc.  Not solved yet.

My last issue, suggestion and comment for the day, as far as I know.  
All is going great with Flexibase.

THANKS.  
-Derek

**Comment by roelmann** [comment]
Thought I already had this but can't see it anywhere, probably from a forum discusssion somewhere then.
Definitely a setting needed as ths is a request in several other themes that use these icons. I think there is also a request to be able to replace them with images rather than FA icons, which I would also look at at the same time.

**Comment by roelmann** [comment]
FA-Icon size setting
https://github.com/roelmann/moodle-theme_flexibase/commit/ac4d5fdf02b1c103b2bc435d28dfa77af3c1f92e
Categories as images rather than icons to be added as 'wishlist' in separate issue - low priority
