### ISSUE TITLE
No preferences in user menu

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#56]
I'm calling the menu top right the user menu.  It seems to have no preferences link.
Is this a feature or a bug?

Flexibase:  No prefs
![82 pref](https://cloud.githubusercontent.com/assets/687780/12796243/a051ec42-cb22-11e5-8cd6-7efbee48baed.png)

Clean:
![82 pref clean](https://cloud.githubusercontent.com/assets/687780/12796250/a8f33464-cb22-11e5-9c48-96029c22ba66.png)

Thanks
-Derek

**Comment by roelmann** [comment]
Have you checked its ticked in the User Menu settings page?

**Comment by roelmann** [comment]
Is it the latest version Derek? The User Menu preferences were added a few weeks ago. One thing I did notice, and Im not sure why, on a clean install, the defaults all pick up properly (such as this being set to Yes) on an upgrade, new settings like this stay as null and need to be changed manually.
I think that's deliberate in the way plugin upgrades generally work (but not sure) as it prevents unintended changes caused by new settings.
![screenshot from 2016-02-03 22 18 04](https://cloud.githubusercontent.com/assets/1045679/12798944/194ef77a-cac4-11e5-95f3-d0d8b76d83fa.png)

**Comment by derekc** [comment]
Version: v3.0.7a - 2016010701
Yes, checked the themes usermenu setting, preferences is there.,

**Comment by derekc** [comment]
Question: sometimes Bob has logged in to see a message "New versions" and has just clicked to upgrade.  What makes this functionality kick in?

I've discovered the current version (from version.php) as $plugin->release  = 'v3.1.0rc';
When do I get a message "Plugins ready to upgrade" and when not?
How do I upgrade to a new version by choice?  Is it the full download zip and uploade (etc)?

Thanks

**Comment by roelmann** [comment]
The "plugins ready to upgrade" notice should be when a new version is released to the plugins database - it shouldn't get triggered by the updates to github. I'm not sure what happens if you have installed a plugin via cloning directly from github in the first place though (I believe it still gives you the upgrade notice based on the database but then warns you that upgrading that way will remove the git access)
If your plugins folders are writable by your moodle webservice (It sounds like they are) then you will be able to do that one-click upgrade for most plugins when they are released to the database.

Certainly the latest version (as of this evening) is that I've just bumped it to 3.1.0RC from the beta - in the last hour or two :) But that is only on github so far - I'll be pushing it out to the database over the weekend after a day or so of final testing. So, for the next day or so, I'm afraid it is just the download from github - either by cloning, or by downloading the zip and uploading to your site (having renamed the folder so you don't get the 'master' bit as experienced previously!)
Its one of those catch22 situations - Id love to put it on the database now, so more people can access it and test it, but I don't want to put a version on there which isn't fully tested and stable or I know someone will end up with it on a production server with a bug.

Current plugins database version - 3.0.7a, Current GitHub Master for release shortly - 3.1.0rc

**Comment by roelmann** [comment]
3.0.7a - Doesn't have the user menu settings and wont have the Preferences in the User drop down - Last commit to github was 24 days ago on the STABLE_30 branch, which is what is on the plugins database
User Menu options were added 11 days ago to Master branch - https://github.com/roelmann/moodle-theme_flexibase/commit/085da658213f0eedb5297919e3d382e6c9d7035c Not yet released to the plugins database

So, if you have 3.0.7 - no preferences. If you have 3.1.0, Preferences is now an option in a new Menu Settings option page, but may have to be turned on manually as an upgrade may not reset the default.
If you have 3.1.0 and the Preferences option is turned on at http://yourmoodlesite/admin/settings.php?section=theme_flexibase_menusettings and its not working then its a bug I need to fix. But its working on both my sites at the moment (development and clean fresh install)

Also, see the new Help pages that can be enabled for the main menu bar from the same settings page (or from http://yourmoodlesite/theme/flexibase/pages/contenthelp.php ) :)

**Comment by roelmann** [comment]
'Yes, checked the themes usermenu setting, preferences is there.,' Just realised what you have checked...
No - in common with quite a few other themes, Flexibase 2 and 3.0 did/do not support the new (at the time of flexibase's initial development) user menu.
Flexibase 3.1 still doesn't support the one from the general themes settings page, it has its own custom user menu setting which overrides that - one reason being flexibase uses fontawesome icons rather than images as used in the general theme one - along with yes/no selectors for a range of menu options on the user dropdown menu. There are no plans to integrate the one from the general theme settings page as this would conflict with the one in the theme, which is more consistent with the rest of the theme settings (in its use of fontawesome icons rather than image based icons)

**Comment by roelmann** [comment]
No issue to fix
'Preferences' menu not supported in earlier versions of flexibase, is already supported in the latest version via its own flexibase theme setting. See  http://yourmoodlesite/admin/settings.php?section=theme_flexibase_menusettings
