### ISSUE TITLE
Error calling/loading js and UI elements on M31

### ISSUE THREAD

**Issue by logan-reynolds** [roelmann/moodle-theme_flexibase#87]
Seeing following error when trying to use this theme due to calling Modernizr javascript before it is defined at /layout/includes/preheaderlogic.php:165 , which caused stylesheets and other UI elements to fail loading:

ReferenceError: Modernizr is not defined

However there apper to be other issues that need resolved since in our tests moving the script include for Modernizr above it's first occurrence still resulted in the malformed view in the browser, indicating the fix may be more extensive.  Recommended fix would be to use AMD loading per https://docs.moodle.org/dev/Javascript_Modules#Embedding_AMD_code_in_a_page

**Comment by roelmann** [comment]
Cannot find any error - on all my systems with flexibase installed (several local host setups and several live sites) Modernizr is working fine, as evidenced by the classes being added to html and as evidenced by the alert wwarnings showing on an IE8 browser.
AMD loading of javascript will be implemented as needed during further development work unless funded to raise its priority. In the meantime this does not cause any breakage of the theme and so will not be fixed in the short term.

**Comment by roglos** [comment]
Solution is to move the <script> line from preheader.php into footer.php below the standard_html line.  Will add the change next time I do a major upgrade.

**Comment by roelmann** [comment]
Solution is to move the script line from the preheader.php into the footer.php below the standard_html line. Will add this next time I do a significant update.
