### ISSUE TITLE
Dotted columns

### ISSUE THREAD

**Issue by fmeneuhe** [roelmann/moodle-theme_flexibase#90]
Hi, when I click "Turn editing on" 1 or even 3 dotted blank  columns like the attached screenshot are showed. What are these columns for?  How can I remove them? 

![dotted_columns](https://cloud.githubusercontent.com/assets/8604933/18316181/ebd79742-7519-11e6-927f-594882f600e6.png)

**Comment by roelmann** [comment]
Those dotted lines were added to highlight the areas that blocks can be dragged into (as a result of a request because people didn't know where those regions were. Checkout the inbuilt theme help on layouts.

The selector is 
.editing .block-region
currently this has a rule
border:3px dotted gray;
You would need to edit that rule to what you want, but you may find you need to replace it with some other way to highlight these possible areas for usability purposes. That's upto you :)

**Comment by fmeneuhe** [comment]
The blocks are empty, so what I want to do is to hide them because they take up space, and I need space. Is possible to hide them?

**Comment by roelmann** [comment]
They disappear as soon as you turn editing back off if empty, so they dont take any space in your design as seen by students. They are only there as a guide during editing - just like the editing menu, the drag and drop icons etc. Empty regions are not visible to most users and so do not take up space in the page as it is used.
You can really only hide them by removing those regions from the layout files/config.
