### ISSUE TITLE
Page blocks button

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#94]
I may have misunderstood Richard, but I thought this was being removed.
![20 page block](https://cloud.githubusercontent.com/assets/687780/18824114/2526e41a-841c-11e6-8ccf-e3af176aa8e5.png)

**Comment by roelmann** [comment]
No, I wasn't removing the blocks page, that was a requested new feature.
What I removed was the fact that the default region was set as one of the
block page regions and that led to confusion when people tried to edit.
It would be quite easy to remove if you don't want it on your particular
site though.
Remove the side-modal regions from config and the button itself from the
layout (I can give more details, if you want to do that, when I am at a
computer rather than from my phone on the train :) )

**Comment by roelmann** [comment]
If you do want to remove it completely, then: In flexibase/config.php remove
https://github.com/roelmann/moodle-theme_flexibase/blob/master/config.php#L48-L50
and
https://github.com/roelmann/moodle-theme_flexibase/blob/master/layout/includes/header.php#L161-L163
